services:
  playwright-desktop:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: playwright_desktop
    working_dir: /app
    shm_size: "2gb"
    ipc: host
    ports:
      - "6080:6080"
      - "5900:5900"
    volumes:
      - ./collector:/app
    tty: true
    stdin_open: true
    environment:
      - TZ=Europe/Rome
      - DISPLAY=:99

      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}

      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

    command: >
      bash -lc '
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 -ac &
        until xdpyinfo -display :99 >/dev/null 2>&1; do sleep 1; done
        fluxbox >/tmp/fluxbox.log 2>&1 &
        x0vncserver -display :99 -rfbport 5900 -SecurityTypes None >/tmp/x0vnc.log 2>&1 &
        until ss -lnt | grep -q ":5900"; do sleep 1; done
        exec websockify 6080 127.0.0.1:5900 --web /usr/share/novnc
      '

  db:
    image: mariadb:11
    container_name: solar_db
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=root
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "13006:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: solar_api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "5002:5000"
    environment:
      - TZ=Europe/Rome
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    command: python api.py

volumes:
  mariadb_data: